### ISSUE TITLE
Is there a way to determine if a class instance has been destroyed?

### ISSUE THREAD

**Issue by tester1101** [wurstscript/WurstScript#1047]
Is there a way to write code like this?

```
class TestClass

function test1()
    let a = new TestClass()
    destroy a
    if isDestroyed(a)
        print("a is destroyed")
        doSomething1()
    else
        print("a is alive")
        doSomething2()

```

**Comment by Frotty** [comment]
There is no reliable way to do this, because object ids are recycled. Thus your references to a destroyed object turn into a valid reference to this new object. Hence checking for "destroyedness" is an *anti-pattern*.
What you should do is cleanup all references of the object when you destroy it, so that there are no references to the destroyed object. In many cases you can avoid having to clear many references by using the observer pattern.

**Comment by tester1101** [comment]
I understand. I need to study the observer pattern. Thanks for the reply.
