### ISSUE TITLE
how to really create a string autohash??

### ISSUE THREAD

**Issue by fbicirno** [wurstscript/WurstScript#1054]
`@compiletime public function string.autoHash() returns int
    return this.getHash()
`
i really need  a string autohash method to save game speed

but its look like not work..
such as
in wurst  "test".autohash()
in game "  stringhash("test") "

**Comment by Frotty** [comment]
I don't understand what you are trying to do here. Hash to save game speed? 
Putting `@compiletime` means the func will be executed once at compiletime.

**Comment by fbicirno** [comment]
I want to convert some strings to hashes at compile time, not in game.

**Comment by cloudfox2** [comment]
You should use `compiletime("text".getHash())`

**Comment by fbicirno** [comment]
> You should use `compiletime("text".getHash())`

The code is too long,not good to read

**Comment by fbicirno** [comment]
![image](https://user-images.githubusercontent.com/50105857/175801048-f5ed2454-012b-4f11-bde4-fcc8da09b9e6.png)
why not work

**Comment by Frotty** [comment]
@cloudfox2 is correct. compiletime() expression are evaluated once at compiletime and then are replaced with the result. Because this is not defined when running the expression in the function body your function evaluates to:
```
function string.autohash2() returns int
    return null
```
If you want to hash your strings your protection I would suggest using specialized software for that like [W3Protect](https://w3protect.eu/) and not do it in source code.
