### ISSUE TITLE
how to use ExecuteFunc in wurst

### ISSUE THREAD

**Issue by fbicirno** [wurstscript/WurstScript#1067]
how to use ExecuteFunc in wurst?

execute()-> has a array limit, i dont want to acces array limit.!!

**Comment by Frotty** [comment]
`ExecuteFunc` isn't related to `execute() ->` because you don't get any information whether the invocation was successful.
`execute() ->` is only array limited in nested execute calls and amount of closures at the same time. If you use it properly it's very unlikely you would hit any limit. Most likely there is some other issue in your code causing this.
