### ISSUE TITLE
Map crashes due to generated jass function with too many arguments

### ISSUE THREAD

**Issue by jlfarris91** [wurstscript/WurstScript#1072]
In Jass the max number of function arguments is 32 and there's a function being generated by Wurst that has 33.

Additionally, I can build the map multiple times in a row and get the same function generated differently each time - some with 33, some with 32.

Last Stand has this problem, not sure what I can do to help sort this out since building the project is a bit involved. Might help for the compiler to throw an exception when it tries to generate a function with more than 32 arguments.

**Comment by Frotty** [comment]
Can you post what functions are having so many parameters?

**Comment by jlfarris91** [comment]
[Bad compiled.j.txt](https://drive.google.com/file/d/15pfk2RDtxdKCeTjFzuIv7llGSxE0EWsT/view?usp=sharing)
[Bad functions](https://pastebin.com/6RTTyTSX)

**Comment by jlfarris91** [comment]
It's odd to me that it's a different function complaining with each compile

**Comment by Frotty** [comment]
`cyc_` indicates this function is used to resolve a cyclic dependency, which you ideally shouldn't have. So consider getting rid of any `initlater` in your packages. The cycle resolution might not be deterministic, which is why it is a different function on different compilations.
Also it seems most parameters are coming from stacktraces, so turning them off should also get rid of the error.
Additionally, the parameter amount seems to stem from using tuples for many things, which isn't ideal either. Consider using classes for data stuff.
Other than updating pjass to detect this error I will not do anything regarding this issue, as it seems non trivial to solve.

**Comment by jlfarris91** [comment]
Oh great, I can give those suggestions a try. Thanks.

Tuples are terribly convenient.

**Comment by jlfarris91** [comment]
I think it would be worth detecting any generated arguments that exceed the limit so that users don't waste time waiting for the game to launch before ultimately crashing.

**Comment by Frotty** [comment]
I updated pjass now to detect functions with too many parameters in jass output.
