### ISSUE TITLE
Add Autocomplete for wc3 resource paths

### ISSUE THREAD

**Issue by Frotty** [wurstscript/WurstScript#407]

**Comment by peq** [comment]
The easiest solution would be to just add constants for all icons, models, and sounds to the standard library.

A really good solution would include a preview of models and icons, search functionality, etc. That would be a lot of work.

So what do you want?

**Comment by Frotty** [comment]
I think model previews would be a bit overkill, but  icon/texture previews should be doable. 
As for the constants, sure generating a big list of constants from the list files would work, but there is also the problem with the names inside the editor being different from the model name in many cases. 
Also what about autocomplete performance? And I wouldn't want them to show always. Maybe have an autocomplete prefix

**Comment by Crigges** [comment]
Some thoughts:
We could put theese constants inside a wrapper class so they wouldn't affect normal autocompletion.

Another problem is the global variable limit, the war3.mpq contains around 10760 files. Ofc not all of them are needed but if each file gets it's own constant the limit will be reached easily. So we could use getter functions instead: 
```
class Assets
    static function ReplaceableTexturesBarrensTreeBarrensTree() returns string
        return "ReplaceableTextures\\BarrensTree\\BarrensTree.blp"

//access the icon
function foo()
    string myIcon = Assets.ReplaceableTexturesBarrensTreeBarrensTree()
```

I think texture previews are pretty nice, and as far as i know OgerLord wrote already a blp2 loader. It also could be difficult to get theese file out of the mpq. Iam not sure if jmpq-v3 is fast enough to load them at runtime. 

Nevertheless I could aready generate a wurstpackage with getter for all .blp .tga .mdx .mp3 .wav .mid files, if you are satisfied with my proposal.

**Comment by peq** [comment]
I had similar thoughts...

I don't think the global variables would be a problem, since Wurst can remove unused variables. 

Maybe we can generate these classes as an intermediate solution. I would prefer to have different classes for models, textures, and sounds. Also it would be nice to get more descriptive names like the ones in WorldEdit (as mentioned by Frotty). We just have to find the files where these names are written.

In the long run, we can probably create a file chooser dialogue with preview for blp files.

**Comment by Cokemonkey11** [comment]
>  Also it would be nice to get more descriptive names like the ones in WorldEdit (as mentioned by Frotty).

I suggest just using aliases - object editor already does this, for example aliasing some item icon names to upgrade icon paths.

**Comment by Crigges** [comment]
> I don't think the global variables would be a problem, since Wurst can remove unused variables. 
> - peq
So i would be a must have to enable the optimizer, wouldn't it?

I just looked up for the files which stores the nice names of the Models and Icons but without success. Any idea where they could be?

**Comment by peq** [comment]
> So i would be a must have to enable the optimizer, wouldn't it?

I am not sure, I think garbage is removed even without the optimizer. If that is not the case it would be easy to change and should be done anyway, I think.

> I just looked up for the files which stores the nice names of the Models and Icons but without success. Any idea where they could be?

Water or Barade might know this.

**Comment by Crigges** [comment]
Ogerlord provides a nice java libary which creates BufferedImage objects out of .blp and .tga files: https://github.com/OgerLord/WcDataLibrary/tree/master/src/de/wc3data/image it should be pretty easy to use this.

I also started working on generating the wurst package: https://github.com/Crigges/Wc3AssetConstants/

There are cases where different models got the exactly same name:
```
Path: buildings\other\CityBuildingSmall90_0\CityBuildingSmall90_0  |  Name: StadtgebÃ¤ude
Path: buildings\other\CityBuildingSmall90_1\CityBuildingSmall90_1  |  Name: StadtgebÃ¤ude
Path: buildings\other\CityBuildingSmall90_2\CityBuildingSmall90_2  |  Name: StadtgebÃ¤ude
```
How would you like to handle this conflicts?
-Use file name instead of the nice on
-Enumerate the occurrence like:
```
Path: buildings\other\CityBuildingSmall90_0\CityBuildingSmall90_0  |  Name: StadtgebÃ¤ude1
Path: buildings\other\CityBuildingSmall90_1\CityBuildingSmall90_1  |  Name: StadtgebÃ¤ude2
Path: buildings\other\CityBuildingSmall90_2\CityBuildingSmall90_2  |  Name: StadtgebÃ¤ude3
```

**Comment by peq** [comment]
Hmm, I think when creating doodads with variations you would sometimes want the path without the number. So maybe try to generate the following constants:

```
Stadtgebäude: buildings\other\CityBuildingSmall90_0\CityBuildingSmall90
Stadtgebäude0: buildings\other\CityBuildingSmall90_0\CityBuildingSmall90_0
Stadtgebäude1: buildings\other\CityBuildingSmall90_0\CityBuildingSmall90_1
Stadtgebäude2: buildings\other\CityBuildingSmall90_0\CityBuildingSmall90_2
```

And of course it should use the English names instead of the German ones.


For the images I have to check how easy it is to include images in the auto-complete descriptions.

**Comment by Crigges** [comment]
> And of course it should use the English names instead of the German ones.
I was just testing with my german mpq files, ofc i will use the english ones for the package :D

Here is a prototype package still with german names: http://peeeq.de/code.php?id=9060

**Comment by peq** [comment]
Nice work :+1: 

Some small suggestions: Remove the type as it can be inferred and sort everything by name.

**Comment by Crigges** [comment]
So this is the package for all models:
http://peeeq.de/code.php?id=9064

The package is generated as following:
The unitui.slk is parsed for all unit objects. With their unit id as key i look up in the 
*UnitStrings.txt files for the proper model name.
Afterwards i parse the doodads.slk for models which aren't included yet, and use the "comment" field as variablename.
Finaly the war3.mpq and war3x.mpq is parsed for other .mdx files which aren't included yet, and use their filename as varibale name.
Any ideas to improve this procedure are welcome.

The wurstscript parser has a with the varnames since they start with a uppercased letter. So should they all start with a lowercased one or just ignore the warnings?

**Comment by peq** [comment]
Some models have two `.mdx` endings.

> The wurstscript parser has a with the varnames since they start with a uppercased letter. So should they all start with a lowercased one or just ignore the warnings?

yes

**Comment by peq** [comment]
Related commit: 5b61d7d45fa3b0e8a31da9e24ff499d82d6b0b55

**Comment by Frotty** [comment]
I don't think a static package is a good solution for this. Similar to code dependencies, you should be able to specify .mpqs from which you want the resources to be shown, so that imports can be shown as well.

**Comment by peq** [comment]
I think it is a good temporary solution until we have a better solution. And we can later adjust the scripts from Crigges to do this automatically at runtime. @Crigges : maybe you can upload the script somewhere.

**Comment by Frotty** [comment]
"Temporary" meaning that it stays till we forget about it? ;)

**Comment by peq** [comment]
Tickets are never forgotten, but there are others with higher priority.

**Comment by Frotty** [comment]
Okay, we are still missing all texture/icon path still though.
What happened to the icon preview for the eclipse plugin @Crigges ?

**Comment by Crigges** [comment]
The texture browser already works as standalone version: https://github.com/Crigges/MpqTextureBrowser
But i have no idea how to include it into the eclipse plugin.

**Comment by peq** [comment]
How should it be invoked? Should I just add a shortcut to launch the browser?

**Comment by Frotty** [comment]
So Icons still missing

**Comment by Frotty** [comment]
Icons and more have since been added
