### ISSUE TITLE
Ternary operator?

### ISSUE THREAD

**Issue by Frotty** [wurstscript/WurstScript#538]
One kinda annoying usecase are lambdas with just one if like:
````
GroupEnum(g, p, Filter(() -> begin
    if GetFilterUnit().getTypeId() == 'z000'
        ...
    else
        ...
end))
````
which requires the begin/end keywords
I would prefer a 1line solution
````
GroupEnum(g, p, Filter(() -> if GetFilterUnit().getTypeId() == 'z000' then ... else ...))
````
which should still allow linebreaks inside it for readability.
Ideally also working without else case for lambdas.
and also this maybe https://github.com/peq/WurstScript/issues/464

**Comment by Cokemonkey11** [comment]
I do like ruby's `action if condition`/`action unless condition` syntax

**Comment by peq** [comment]
Oh god, I hate that Ruby syntax. (Mostly because it evaluates code backwards, from right to left).

Interestingly, Ruby returns `nil` if there is no default value. In Wurst we could return the default value for the expected type instead, but that might be a bit surprising for users.

For example `int x = if 4<3 then 2` would result in x being `0`.

Another option would be to always require the else-branch. And maybe later add an exception for places where no return-value is needed.

**Comment by Cokemonkey11** [comment]
My second preference would be c-style ternary `int x = 4 < 3 ? 2 : 0` (and require both branches)

**Comment by Frotty** [comment]
I don't think adding ? and : as symbols is a good idea.

**Comment by IgorSamurovic** [comment]
Why, though, is there any problem with ? and :? Or did you plan to use it for something else? The way I see it ? : should be pretty decent.

**Comment by Frotty** [comment]
Two new symbols just for one purpose. Maybe not so fitting with the rest.

**Comment by peq** [comment]
The benefit of `_ ? _ : _` would be that it fits well with our linebreak rules: We could just say that linebreaks are allowed after `?` and before `:`. With `if _ then _ else _` we could allow a linebreak after `then`, but `else` is already used so we cannot change the rules here. `if _ then _ otherwise _` or a `\` for ignoring linebreaks would be other options, but I don't like them very much.

It would also be possible to use `if _ then _ else _` and use linebreaks with indentation, but then it would not be legal to write something like this:

    GroupEnum(g, p, Filter(() -> 
        if GetFilterUnit().getTypeId() == 'z000' then 
            ... 
        else 
            ...)) // missing end-indentation here

**Comment by IgorSamurovic** [comment]
I honestly think the _ ? _ : _ approach is the best because it is very intuitive, used in a shitload of languages (so it is a good thing to get used to, even if you haven't even programmed before, and if you have programmed before, it will come naturally to you), I find the if _ then _ else _ approach to be weirdly verbose compared to other wurst syntax which you guys have done everything to rid of such redundancy, especially since "then" is not used in wurst. I don't think suddenly adding it is smart.

I understand how other approaches might be more fitting for wurst in some ways, but this isn't something that can really be improved too much, it's a matter of semantics, really. For most uses you just want something that's simple, quick to type, understandable to people who code, etc, it's easy to overthink this.

I have coded in C family of languages for over 12 years so I am really used to the _ ? _ : _ approach, therefore it's also important to keep in mind that my opinion might be way too clouded by that, though.

If the _ ? _ : _ implementation is as intuitive as peq says, then it's really probably the best one to implement. The only real downside I can see here is that you guys might figure an amazing way to include : or ? symbols for something else, while if _ then _ else _ is unambiguously exactly that, though it has the drawback that peq mentioned.

**Comment by peq** [comment]
Is now implemented with the `_ ? _ : _` syntax. Please don't use it too much, only for small expressions.

**Comment by IgorSamurovic** [comment]
Does it work with begin-end blocks? Obviously using them would be stupid, I just wonder if it is possible.

**Comment by peq** [comment]
Yes, you could do something stupid like this:

    int x = 0
    int y = 1 < 3 ? begin
        x = 40
        return 2
    end : begin
        x = 60
        return 3
    end

But you should not ;)

**Comment by peq** [comment]
PS: if the ugliness is not enough to keep you from doing it -- this is the code that gets generated from the example above:

	local integer x = 0
	local integer y
	local integer cond_result
	if 1 < 3 then
		set x = 40
		set cond_result = 2
	else
		set x = 60
		set cond_result = 3
	endif
	set y = cond_result

**Comment by IgorSamurovic** [comment]
Jesus that's ugly. I was mainly wondering if it is possible because I knew that if it were, it'd be ugly as hell. So thanks for proving that in an example. Not that this should ever be relevant, because nobody should do this, ever.

**Comment by Frotty** [comment]
@IgorSamurovic __ot__: is your bonusmod using closures available yet?
