### ISSUE TITLE
Block comment problem

### ISSUE THREAD

**Issue by DDLegionTN** [wurstscript/WurstScript#575]
When doing this thing :
```
/**/

/**/
```
```
/**/
function A()
    skip
/**/
```
Both of them gave me syntax error, even it seem to be no problem.

**Comment by Frotty** [comment]
1. I don't get a syntax error for the code you posted. Please provide complete example with the message of the error. not just "i got error".

2.
Block comments look like this
```
/* */ <- block comment
```
By doing `/**` you indicate the start of a hot doc which expects another closer.
```
/** */ <-hot doc
```

**Comment by DDLegionTN** [comment]
Oh so what causes the problem is /**, since were used to the comment block in such form.

I know error need to be specific. I assume such problem can be easily produced hence didn't upload the error message. The error message :

[Wurst] no viable alternative at input '/**/\r\n\r\n/**/<EOF><EOF>'

for 

'''
/**/

/**/
'''

Error message :
[Wurst] no viable alternative at input '/**/\r\nfunction A()\r\n    skip\r\n/**/<EOF><EOF>'

for another one.

Btw may I know what is hot doc?

**Comment by Frotty** [comment]
Alright, I get the error now too. As I already explained it is due to Wurst parsing `/**/` as `/**` being the start of a hot doc - document comment. However this is still a bit strange because apparently the second slash is wrongly parsed.

Hot Doc is Wursts' documentation generator. If you write a comment starting with `/**` above a function, variable, class etc. it will be shown in vscode:
![](https://i.imgur.com/lwDH6nh.png) 
![](https://i.imgur.com/CPxudrb.png)
and can generate some .html output (very ugly right now, needs an update)
![](https://i.imgur.com/QG8rxAP.png)

**Comment by DDLegionTN** [comment]
Ah I see, pretty neat feature, thanks for your explanation.

**Comment by peq** [comment]
I think the main problem here was, that Vscode did not highlight the comments correctly. I pushed an update to fix this now.

Here is how your example looks like now:

![](https://i.imgur.com/il5T6I2.png)

The comment starts with `/**` and ends with the next `*/` after that.

Also important to know: Hotdoc comments are not like other comments -- they can only appear at certain places in the source code (e.g. in front of a function) and when used in different places you get a syntax error.
