### ISSUE TITLE
Infer type in lambda expression

### ISSUE THREAD

**Issue by Frotty** [wurstscript/WurstScript#624]
1. Infer type in lambda expression
current:
```
(int i) -> x+i
```
This should also work:
```
(i) -> x+i
```

Additonally it would be nice if `it` could be used in single value lambda expressions
```
(int i) -> x+i
```
Since it's only one param, we should get rid of the `() ->` part
it is already a reserved keyword, even though it doesn't seem to be used.
```
(x+it)
```

**Comment by peq** [comment]
Started working on this on branch https://github.com/wurstscript/WurstScript/tree/lambda-infer 

The part with `it` is not yet implemented, but parameters without types should work (for some cases). If you want to help, check out the branch and see if it breaks anything in your projects (and then try to remove some type annotations in lambda expressions).

**Comment by peq** [comment]
This is now merged into master. 

Instead of `(int i) -> x+i` one can write `(i) -> x+i`. 

For lambdas with one or zero parameters, parenthesis around parameters are optional: `i -> x+i` is also possible.

I am not going to add the `it` Syntax, because it only saves 4 characters and adds another special case that is hard to explain.
