### ISSUE TITLE
IntelliJ support

### ISSUE THREAD

**Issue by mvlabat** [wurstscript/WurstScript#626]
Hello! Is there any chance to witness IntelliJ support? :)

I can see you guys are quite familiar with Java, and I wonder why you chose VSCode as the primary Wurst supported platform. ) I would love to hear whether there are any plans for IntelliJ support. If you need any help, I'll try to get in touch with my colleague who had experience in developing Rust plugin for IntelliJ.

**Comment by Frotty** [comment]
These are soe of the reasons.
-IntelliJ doesn't have native LSP support. There is a [plugin](https://github.com/gtache/intellij-lsp) though
-An additional plugin means additional maintenance
-Intellij is a heavy download, and and only the community edition is "free" and partially open source.
-IntelliJ is much more purpose-fit to Java (I think it even requires JDK by default?) - vscode is a more generic, lightweight editor.

We don't have any plans making a plugin for IntelliJ, and unless the integration with the plugin is hasslefree und useful, this doesn't have any priority.

**Comment by mvlabat** [comment]
Well, that sounds reasonable. Thank you for the answer )

But a word about the two last points: I think it's for developer to decide, whether they want to use such products or not. I myself don't mind using IntelliJ for developing non-Java applications. I just find IntelliJ extremely comfortable to use as an editor, I had no such experience with any of others. I don't mind JDK either. Anyway, we're developers, it's okay to have such things on our systems. )

Though I totally understand that it means additional maintenance for you and you may have no resources available for it.
If I have some spare time, maybe I'll try to dig into it myself. That would be very interesting experience for me. But I have no false hopes that it would be finished some day :D

**Comment by Frotty** [comment]
> [...] I think it's for developer to decide, whether they want to use such products or not. I myself don't mind using IntelliJ for developing non-Java applications. [...]

Yes, but many warcraft 3 mappers aren't (experienced) developers. Before vscode we used eclipse, and got many complaints about the big filesize, jdk requirement, bad plugin infrastructure, etc.

Of course you are very welcome you develop a third party plugin 👍

**Comment by peq** [comment]
The main reason for vscode is that it was the first to propose the [language  server protocol](https://github.com/Microsoft/language-server-protocol), which offers a very nice API for building language plugins. When we started with the plugin, vscode had the best support for the protocol, but now other editors are adding support as well. So in theory is would not be much work (I guess around a week) to support another editor like IntelliJ.

Now both Eclipse and Intellij somehow support the language server protocol, but before that, when we were still on Eclipse, the situation was much worse.

The native plugin API of Eclipse, which we used before, is just a big fat MESS. Basically you have to implement every little editing feature on your own and there is no clear API that you can depend on. However, Eclipse plugins are very flexible in what they can do.

IntelliJ had a kind of different approach. Basically IntelliJ wanted you to write plugins, by implementing the complete parser, type checking, etc AGAIN using their API (PSI based). That means you cannot use most of the code you already have for your editor. Because of this, there actually are a lot of language plugins for IntelliJ which work kind of well for simple cases, but fail in more complex cases when the editor type checking does not exactly match the compiler type checking.

> If you need any help, I'll try to get in touch with my colleague who had experience in developing Rust plugin for IntelliJ.

If he did it using the official [Rust language server protocol](https://github.com/rust-lang-nursery/rls), then it would probably be easy to adapt to Wurst.

**Comment by mvlabat** [comment]
Thank you for your detailed answer!

As far as I know, Rust LSP was not used, so yes, it required a lot of work to write that plugin.

**Comment by Frotty** [comment]
Closing this stale issue. Was there ever any progress on this?
