### ISSUE TITLE
More lambda syntax stuff

### ISSUE THREAD

**Issue by Frotty** [wurstscript/WurstScript#627]
Works:
```
forUnitsInRange(pos.toVec2(), AREA_OF_EFFECT) u ->
	skip
```
Doesn't work, would be nice if it would:
```
forUnitsInRange(pos.toVec2(), AREA_OF_EFFECT, u ->
	skip)
```

What about cases where the closure is not last param?:
```
//Works:
foo(12) vb -> 
	print("")
//Works also:
foo(vb -> print(""), 12) 

//Doesn't work, but would be nice
foo(vb -> 
	print("")
, 12) 
```

**Comment by peq** [comment]
The main problem here is the combination with the [line breaking rules](https://wurstlang.org/manual.html#syntax): For example a newline is ignored before `,`. Therefore, your example would be equivalent to 

```
foo(vb -> 
	print(""), 12) 
```

And this is not allowed, since the block end is not visible by indentation.

To the parser it looks like `foo(vb -> NL START_BLOCK print(""), 12) END_BLOCK`.

Similarly, your earlier example would be seen as `forUnitsInRange(pos.toVec2(), AREA_OF_EFFECT, u -> NL START_BLOCK skip) NL END_BLOCK`.

I don't really want to change the rules for ignored newlines, since I think they are quite simple and work well as they are now.

If you have any ideas on how to integrate this into the current rules, let me know.

**Comment by Frotty** [comment]
I think it's okay for now
