### ISSUE TITLE
how to overwirte a baselib function

### ISSUE THREAD

**Issue by PhoenixZeng** [wurstscript/WurstScript#633]
i want overwirte  the string.toInt() but it not work
even i try to make a string_config and @config my function but it still use the lib function
the only way to use my same-name function is import nowurst but it is not a good idea

**Comment by Frotty** [comment]
You can't. Only functions annotated with **@configurable** are eligible to be configured.
Primitive functions like `#.toInt()` aren't supposed to be configured, because other packages in the standard library use them and changing them could lead to unexpected, erroneous behavior.
You should be able to simply write a new function that does what you want.
Again, please remember that github issues are meant primarily for bug reports and feature requests/discussions. You can ask simply usage questions in our ![irc channel](https://webchat.quakenet.org/?channels=#inwc.de-maps) or on ![the hive](https://www.hiveworkshop.com/forums/triggers-scripts.269/) as thread or PM.
