### ISSUE TITLE
support : for player p in force

### ISSUE THREAD

**Issue by PhoenixZeng** [wurstscript/WurstScript#649]

**Comment by Frotty** [comment]
Iterators are part of the standard library, not compiler.
In any case, forces are very limited and don't provide a native `FirstOfForce` like group and therefore there isn't an elegant way to make an iterator.

I suggest just using `LinkedList<player>` instead of force.
If you have a good implementation suggestion, open a new ticket in the [standard library](https://github.com/wurstscript/WurstStdlib2).
