### ISSUE TITLE
check if one object has destroyed

### ISSUE THREAD

**Issue by cloudfox2** [wurstscript/WurstScript#681]
now i have to add a flag to check this

i think object should be null after it is destroyed

**Comment by peq** [comment]
There can be many variables pointing to an object (aliases). If we wanted to set all these variables to null, we would need to keep track of these variables, which would be a big overhead. Also it's difficult because you can cast an integer to an object in Wurst. It's also difficult to set local variables in other function invocations to null.

So this is to complex to implement. I'd rather implement automatic reference counting, so that we don't need to destroy objects manually.

Btw: if you are accessing an attribute of an destroyed object, you are doing it wrong. Object ids are reused for newly created objects, so you will most likely get strange bugs if you do this.

**Comment by cloudfox2** [comment]
my point is to check destory
i need to check this because destroy twice would get a double free warning

maybe i can just ignore this warning?

**Comment by Frotty** [comment]
Destroying an object two times is an error you are causing by the way your code is working. Ignoring warnings isn't good. Better design and implement your code in a way where you don't destroy objects two times.

If you don't want to change your whole code, you can add a boolean to the class yourself, indicating whether it's destroyed.

**Comment by peq** [comment]
> If you don't want to change your whole code, you can add a boolean to the class yourself, indicating whether it's destroyed.

If you do this you should not destroy your object at all. Accessing a field of a destroyed class is a programming error.

If you show us your code, we can show you how to properly avoid double frees. Often  it's a good strategy to think about who owns an object.
