### ISSUE TITLE
Provide a way to read SLK in batch?

### ISSUE THREAD

**Issue by ftdcs** [wurstscript/WurstScript#682]
like YDWE,it provide a lua engine,we can easier to batch operation slk.
In fact, its principle is to replace lua variable with string before jasshelper compilation.
its useful features when you need simulation a system.
for example you want to simulate shop,You need to maintain the items you need one by one.
In YDWE you just loop slk.item and filter you want.
The same is better for the decoupling of the map.

Search the ability of hotkey for T.
![qq 20180630110205](https://user-images.githubusercontent.com/37105952/42120865-56730552-7c55-11e8-9fc5-9cdf4d7409da.png)

**Comment by peq** [comment]
I am not sure, I understand. 

1. Do you want to read an external SLK file or do you want to read the objects stored int the map?
2. If you want to read the objects stored in the map: Should this include objects created by Wurst?
3. Would it be enough if we made it possible to read existing objects at compiletime?

It would be nice if you could post links to some systems using this feature of YDWE, so that we can see how it is used and what is needed to support the use cases.

I don't want to add anything that is based on text replacement in the code, but maybe we can do something else. If you want text-replacement it is probably possible to run the same YDWE preprocessor on Wurst files, so we don't need to integrate it into the Wurst compiler.

**Comment by Frotty** [comment]
I don't get it.
In Wurst you should just use our ObjectEditing and not need this at all?

**Comment by ftdcs** [comment]
1. I want to read the objects stored in the map 
2. I think it is not particularly important to include objects created by wurst. wurst objectEditing  is more suitable for implementing portable libraries.
3. I think its enough.
I just want wurst can read slk and injection to a object list...

**Comment by Frotty** [comment]
> I want to read the objects stored in the map

Wurst exports all objects in wurst code if you run/build a map. see `_build/objectEditingOutput`.
If you modify/extend the objectdef to save your values, you can access them. The only thing missing here is perhaps reading existing data fields for units.

> I think it is not particularly important to include objects created by wurst. wurst objectEditing is more suitable for implementing portable libraries.

No idea what you mean by this.

> I think its enough. I just want wurst can read slk and injection to a object list...

Wurst uses https://github.com/inwc3/wc3libs for wc3 data handling. I am working on fixing slk support right now actually, and we will use it in the future.
But not for injection like you suggested, but exposing existing fields for all units by reading them from the game's and the map's slk files. Using the wurst objectEditing classes then, you can access these values coherently and safely.

And as peq said, if you want to run some sort of binary as a preprocessing task, you can do that using vscode's task structure (e.g. jasshelper). This doesn't belong into the wurst compiler.

**Comment by ftdcs** [comment]
I probably understand what you mean. Thank you for your reply. Also look forward to the subsequent update of wurst objectEditing classes.

**Comment by Frotty** [comment]
see #683
