### ISSUE TITLE
Improve error message when extending class without no-arg constructor

### ISSUE THREAD

**Issue by dkinvoker** [wurstscript/WurstScript#703]
It is impossible to extend class without "constructor()"
Wurst error inside subclass: Incorrect call to super constructor: Missing parameters

**Comment by Frotty** [comment]
That's a user error, but I suppose the error message could be improved.
The constructor of your subclass needs to call the constructor of your superclass.
If you explicitly define a constructor, you automatically get rid of the no-arg constructor, and thus the class cannot be created, since it doesn't know what parameter to pass.

This is your example:
```
class A
	construct(int i)

class B extends A
```
Your example with the implicit no-arg constructor of `B` visualized:
```
class A
	construct(int i)

class B extends A
	construct()
		super()
```

Now the error should make more sense.

**Comment by Frotty** [comment]
You're welcome! Please consider starring our main repo if you enjoy wurst 👍

**Comment by peq** [comment]
> I was a little confused cuz' i'm a C# developer, and i'm used to fact that if superclass do not include no-arg constructor the subclass do not have it either, and there is no need to specify parametrical constructor that simply calls super-constructor to make compiler know not to generate constructor() within subclass.

Actually it is the same in C#:

```
class A {
	public A(int x) {
	}
}

class B : A {
}
```

> Compilation error (line 6, col 7): 'A' does not contain a constructor that takes 0 arguments
