### ISSUE TITLE
make the module can be function`s params

### ISSUE THREAD

**Issue by PhoenixZeng** [wurstscript/WurstScript#734]
if a class use a module 
then it have all field and function in the module

so . why a function cant have a module param?
```
module A
    function getxxx( ) return int
      return 2
class B use A

function aaa(A a)
   print(a.getxxx())
init
    print(new B())
```

**Comment by peq** [comment]
Modules are not types.

The suppose of modules is to allow reusing implementations without creating type-dependencies. In the translation to Jass we have to share the same id-pool for all objects of a related type. Since we don't always want this we have modules in the language. If you want this type relation you can use (abstract) classes and interfaces, e.g.:

```
class A
    function getxxx( ) returns int
        return 2

class B extends A

function aaa(A a)
    print(a.getxxx())
init
    aaa(new B())
```

So this is the reason why it's not currently possible to use modules as types. 

To support your suggestion, we need some more detailed proposal on how this could be translated. If we allow modules as types, you could also have global variables with a module type and so on.
