### ISSUE TITLE
Can a static method be called through an instance?

### ISSUE THREAD

**Issue by GetLocalPlayer** [wurstscript/WurstScript#750]
```
package Hello

class Test
	function hello()
		print("Hello, World!")

	static function damn()
		skip


init
	let t = new Test()
	t.hello()
	t.damn()
```

raises 

```
There was an error when compiling the map:
Error in File Hello.wurst line 14:
Could not find dispatch for Hello_Test_damn
```

**Comment by Frotty** [comment]
Should be an error imo. Static funcs are just normal funcs that you keep inside the class for organization and API reasons. Calling from instance can be confusing to the writer and the reader since it doesn't have anything to do with the instance. I think it is permitted in some languages, but not recommended.
