### ISSUE TITLE
Autocomplete is inconsistent

### ISSUE THREAD

**Issue by Kyromyr** [wurstscript/WurstScript#769]
Autocomplete results differ based on how it was opened (typing or shortcut), and several other criteria that I havn't been able to narrow down. Based on input it can match by substring, by prefix, and/or by checking if all the characters in the input are present in the matched string.

Recording demonstrating the issue: [Dropbox](https://dl.dropboxusercontent.com/s/r04wj3cox70qutr/2018-11-29_18-29-25.mp4)
[languageServer.log](https://github.com/wurstscript/WurstScript/files/2630242/languageServer.log)

**Comment by Frotty** [comment]
Looks like expected vscode behavior to me.because the autocomplete data doesn't get refreshed by the language server as you type, but by the code client.

**Comment by peq** [comment]
Currently Wurst tries out different search strategies and uses the first strategy that results in a nonempty completion list.

1. Only search names that start with the already entered text.
2. Search names with the already entered text as a substring.
3. Search names with the already entered text as a subsequence.

When Vscode has a list of completions and we tell Vscode that the list is complete, then Vscode seems to use the subsequence strategy.

I see two ways to change the current behavior:

1. We can tell Vscode that the completion is not complete if strategy 1 or 2 were used. This means Vscode will send a request on every change and the results would be consistent. However, this would of course be a bit slower.
It is still inconsistent in a sense that a longer search string can result in a longer list of suggestions.
2. We can only use the subsequence strategy so that we are consistent with how Vscode handles it.

You can try out the strategies by building Wurst from branches `completions-strategy-1` and `comletions-strategy-2`. I am not sure which one is better. Maybe just use them for some time and then tell me which one works better ;)

**Comment by Frotty** [comment]
Without feedback from @Kyromyr I'm gonna close this.
I haven't tested the strategies but the current situation seems pretty good, unless you have a very weak machine like an old laptop, where the wurst response time is slow. Can open a new ticket for that if necessary.
