### ISSUE TITLE
Add warning if repeated type should be inferred

### ISSUE THREAD

**Issue by Frotty** [wurstscript/WurstScript#816]
~~If variables are initialized like `int i = 0` by convention the type should be inferred, e.g. `var i = 0`.
Just like tslint the former should throw a warning.~~
`Bratwurst bratwurst = new Bratwurst` duplicates "Bratwurst" and should be defined with let/var instead.

**Comment by peq** [comment]
This should be up to the programmer. Sometimes code is more readable with more type annotations.

Maybe cases like `Bratwurst bratwurst = new Bratwurst` could give a warning because of the repetition. 

But `Bratwurst w = factory.make()` is more readable than `let w = factory.make()` since in the latter I need to know that the `factory` is a `BratwurstFactory` and that the `make` method will thus return a `Bratwurst`.

This gives some good guidelines on when to use type inference: 
https://openjdk.java.net/projects/amber/LVTIstyle.html

**Comment by Frotty** [comment]
> This should be up to the programmer. Sometimes code is more readable with more type annotations.

Well all warnings are up to the programmer as they are technically legal code, but discouraged. I think this rule should still optionally be part of the "wurstlint" checker.

> Maybe cases like Bratwurst bratwurst = new Bratwurst could give a warning because of the repetition.

sounds good.

> But Bratwurst w = factory.make() is more readable than let w = factory.make() since in the latter I need to know that the factory is a BratwurstFactory and that the make method will thus return a Bratwurst.

I think this is a somewhat lacking example as the confusion can be solved just as good by proper naming. Name the factory `bratwurstFactory` implying the return type, and the local `bratwurst` or `wurst`.

If the type can be inferred by the context, it means your code has great naming and API.
