### ISSUE TITLE
Build: Map Name Exception

### ISSUE THREAD

**Issue by maltebp** [wurstscript/WurstScript#874]
If you create a new map, and don't change the **map** name from within the editor, Wurst will throw an exception when trying to build the map (see logs).

The problem will disappear by either:
 1) Change the map name within the editor (you can delete a letter, save the map, put it back, save again, and it'll work) 
 2) Remove the 'fileName: MyMapFile'  line in the _wurst.build_

The map name seems to be empty (despite it saying "Just another... ") until you manually change it.

**To Replicate problem**
 1) Create new wurst project
 2) Create new TFT map (just place a bloodelf)
 3) Try to run the map from VSC - it should throw the error
 4) Change the map name from within the editor or remove the mentioned line
 5) Map should work fine now

Specs: 
 - Compile build 1182
 - WC3 Version: 1.31.1.12164 x86_64

**Note:**
- It's new problem, as I've been able to run the maps previously
- The standard ExampleMap.w3x in a new Wurst project works fine, as the map name has been changed

[vsc_wurstOutput.txt](https://github.com/wurstscript/WurstScript/files/3382897/vsc_wurstOutput.txt)

[languageServer.log](https://github.com/wurstscript/WurstScript/files/3382895/languageServer.log)

**Comment by WaterKnight** [comment]
Seems to be a consequential error because it reads a w3i with a priorly invalid game data set. I don't know if it was that way before but I have tested the outputs of the WE and if you don't touch the game data set, it encodes as -1 (FF FF FF FF) instead of 0 (standard/depending on melee map state) although this still appears to semantically refer to standard.

**Comment by Frotty** [comment]
Should be fixed now, thanks for the report 👍
