### ISSUE TITLE
Base type object for all types to make casting easier

### ISSUE THREAD

**Issue by jlfarris91** [wurstscript/WurstScript#896]
I want to write a function to support any class instance type (but not be generic) and the only way I can do that now is to convert instances to type int and back.

From my previous post about generic/custom events where I want to inform the event handler which object raised the event:

```
  function invoke(int sender, T args)
    if (_handlers != null)
      for handler in _handlers
        handler.callback(sender, args)
```

So for now this is how I do it but it would be nice to have proper support for what is effectively a base class for all class types that allows for easier casting. Of course this still means that there's a chance for invalid casting but I'd take an assert over casting to int and back.

**Comment by Frotty** [comment]
A base object would mean that all classes would share the same id range, which would be very counter beneficial.
In Wurst you should avoid to ever cast to and from int.

**Comment by jlfarris91** [comment]
Okay, the id range issue makes sense. I don't see why casting to int is a bad idea since all objects are ultimately just integer identifiers anyways and they necessarily can't change during their lifetime. Seems pretty safe to me outside the possibility of casting failures - but maybe I'm underestimating how negative the consequences might be?

**Comment by Frotty** [comment]
Because with Wurst we try to keep the language use high level if possible.
It is an unsafe, unchecked cast and therefore should be avoided.
You also lose strict type safety at compile time, which is one of the strengths of wurst.
You have to take special care in cases to cast ints back to their correct class and destroy them, and avoid ids being recycled making your int reference a different object.
Also with the lua backend and other planned features, casting to int might be forbidden for "managed" classes to ensure safety.

In some cases it is fine, or even necessary to have access to the object id, e.g. low level library optimization or where typing is impossible, like unit user data. But your should encapsulate those casts as much as possible and should not be passing objects around as ints, or have the API expect ints to be of a certain type.
