### ISSUE TITLE
WurstScrupt Discord server

### ISSUE THREAD

**Issue by jlfarris91** [wurstscript/WurstScript#943]
I didn't see a suggestion for this yet but I would really prefer to communicate via Discord rather than the Chat app that you guys currently use. Any thoughts on this?

**Comment by Frotty** [comment]
Discord is spyware and not a FOSS product.
We don't use an "app", [IRC](https://en.wikipedia.org/wiki/Internet_Relay_Chat) is a protocol, you can connect with any client/app you want, the link on the page is simply a web-client.
There is also a matrix room which you can access with riot, which is closer to discord, see http://matrix.org/#wurst

Many wurst contributors prefer these options over discord, which is why there is no official server.
