### ISSUE TITLE
Can we have !nowurst flag in j files?

### ISSUE THREAD

**Issue by netVoix** [wurstscript/WurstScript#947]
I often works with legacy code and with memhack and i cant use wurst because of errors (dynamic ExecuteFunc, return bug etc). Can i have an option not to check errors in the whole war3map.j or maybe only in part of this file?

**Comment by Frotty** [comment]
Since Wurst isn't just checking errors but parsing the .j files so it can combine them with the rest of the model, I don't think this is an adequate solution. 
You can disable pjass which checks the output war3map.j with `-noPjass`, but this will have no effect on input .j files.
You probably have to do a second compilation with jasshelper or whatever accepts your bug code.

**Comment by netVoix** [comment]
Ok. Got it. Now i just need to comment a couple of error rows and then uncomment them after compile )
