### ISSUE TITLE
Dynamic dispatch works unexpected when using it as a member.

### ISSUE THREAD

**Issue by Legend94rz** [wurstscript/WurstScript#959]
## reproduce steps
Here is the example code:
```
package testDynamicDispatch
import ClosureTimers

public class Base
    Base next
    function clear()
        print("Base Clear")
        if next != null
            next.clear()

public class SubClassA extends Base
    override function clear()
        super.clear()
        print("SubClassA Clear")

public class SubClassB extends Base
    override function clear()
        super.clear()
        print("SubClassB Clear")

init
    doAfter(0)->
        let suba = new SubClassA()
        let subb = new SubClassB()
        suba.next = subb
        suba.clear()
```
The expected output is:
```
Base Clear
Base Clear
SubClassB Clear
SubClassA Clear
```
However, the actual output is:
```
Base Clear
Base Clear
SubClassA Clear
```
I suspect the type of `subb.next` is `class Base` rather than `class SubClassB`, which is incorrect.

**Comment by peq** [comment]
Wurst has this special rule, where recursive calls to the same method are bound statically. 
The bug here was that it would also treat a call as recursive if it was not a call on 'this'.

The problem with recursive calls with dynamic dispatch is that there is no efficient way to translate them to Jass. 
So this rule was to optimize the generated code. 
Now, it should work as expected but Wurst will translate this by creating one big method for `clear` and all its submethods.
